kind: Service
apiVersion: v1
metadata:
  name: my-awesome-service
spec:
  selector:
    app: kubernetes-dashboard
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443


cat << EOF | kubectl create -f -
kind: Service
apiVersion: v1
metadata:
  name: nginx-to-local-host-30080
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
EOF

cat << EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: prometheus-1-grafana
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
EOF


 kubectl create clusterrolebinding mbanica binding \
 --clusterrole=cluster-admin \
 --user=mbanica@paloaltonetworks.iam.gserviceaccount.com